apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: queuecure-secrets
  namespace: queuecure
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: queuecure-secrets # Name of the secret to be created in kubernetes
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: queuecure/production # Name of the secret in AWS Secrets Manager
