apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: queuecure-ingress
  namespace: queuecure
spec:
  rules:
  - host: queuecure.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: queuecure-service
            port:
              number: 80
